build:
	cp package.json pkg/package.json
	cp package-signer-wasm-browser.json pkg/browser/package.json
	cp -r js pkg/
	cp -r rpc pkg/
	cp package-signer-js.json pkg/js/package.json
	cp package-signer-rpc.json pkg/rpc/package.json
