### Send POST request with json body
POST http://filecoin1.rosetta.zondax.ch:1235/rpc/v0
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "Filecoin.StateNetworkName",
  "params": [],
  "id": 1
}
